services:
  - type: web
    name: gamepass-db
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PORT
        sync: false
      - key: DATABASE
        sync: false
      - key: PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.9